<a href="https://colab.research.google.com/github/sandeepkhannavp/SCIENTIFIC-COMPUTING-LAB/blob/main/SCL_PS_2_20PT29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sympy import *
import sympy as sp

**Q1** - Write a python program to find the eigen values and eigen vectors of
the following using direct method?

In [4]:
def eigenValues(matrix):
  l = symbols('lambda')
  order = len(matrix)
  I = np.identity(order, dtype = int)
  lI = I * l
  expr = Matrix(lI - matrix).det()
  eigValue = solve(expr)
  return eigValue

In [ ]:
def eigenVectors(matrix, eigValues):
  eigVectors = []
  order = len(matrix)
  I = np.identity(order, dtype = int)
  zeros = np.zeros((order, 1), dtype = int)

  for e in eigValues:
    m = (e * I) - matrix
    m = Matrix(m)
    aug = m.rref()[0]
    vec, params = aug.gauss_jordan_solve(Matrix([0] * order))
    taus_ones = {tau:1 for tau in params}
    vec = vec.xreplace(taus_ones)
    eigVectors.append(np.array(vec))

  # for i in range(len(eigValues)):
  #   lcm = 1
  #   denominators = [Fraction(x).denominator() for x in eigVectors[i].flatten()]
  #   for j in denominators:
  #     lcm = lcm * j // gcd(lcm, j)
  #   eigVectors[i] = eigVectors[i] * lcm

  return eigVectors

In [ ]:
matrix = np.array([[-5, 2], [-7,4]])

In [ ]:
eig_val = eigenValues(matrix)
eig_vect = eigenVectors(matrix,eig_val)
for i in eig_vect:
  print(i)

[[1]
 [1]]
[[2/7]
 [1]]


**Q2** - Write a python program to diagonalize the following matrix.

In [ ]:
mat1 = np.array([[1, 0], [6,-1]])
eig_val = eigenValues(mat1)
eig_vect = eigenVectors(mat1,eig_val)
P = Matrix(eig_vect[0])
for i in range(1,len(eig_vect)):
  P = P.col_insert(i,Matrix(eig_vect[i]))
P = np.array(P,dtype=float)
PI = np.linalg.inv(P)
res = PI @ mat1 @ P
print("After diagonalisation : \n",res)

After diagonalisation : 
 [[-1.  0.]
 [ 0.  1.]]


**Q3** - Write a python program to change the following quadratic form into
canonical form

In [ ]:
x = sp.var('x')
y = sp.var('y')
z = sp.var('z')

def CalculateEigenVectors(A,l):
    
    length = A.shape[0]
    I = sp.eye(length)
    Z = I.multiply(l)
    H = A-Z
    J = H.nullspace()
    return J
    
def CalculateEigenValues(A):

    length = A.shape[0]
    I = sp.eye(length)
    Z = I.multiply(x)
    H = A-Z
    DET = H.det()
    L = sp.solve(DET,x)
    l = []
    for i in L:
        k = CalculateEigenVectors(A,i)

        for j in range(len(k)):
            l.append(k[j].tolist()) 

    M = np.empty((A.shape[0],len(l)))

    for i in range(len(l)):
        for j in range(A.shape[0]):
            M[j][i] = l[i][j][0]

    N = np.linalg.inv(M)
    K = N.dot(A)
    K = K.dot(M)
    
    print("\nSymmetric matrix after Diagonalisation: ")
    return (K.astype(int))
    
def main():    
    
    n = int(input("Enter no. of variables: "))
    expr = sp.sympify(input("Enter the Quadratic form: "))
    symmetric_matrix = [[] for  i in  range(n)]
    
    if n == 2:

        symmetric_matrix[0].append(expr.coeff(x**2))
        symmetric_matrix[0].append(int(0.5*(expr.coeff(x*y))))
        symmetric_matrix[1].append(int(0.5*(expr.coeff(x*y))))
        symmetric_matrix[1].append(expr.coeff(y**2))
        print("\nSymmetric matrix for given Quadratic form is: ",symmetric_matrix)
        SYMMETRIC = sp.Matrix(symmetric_matrix)
        diag = CalculateEigenValues(SYMMETRIC)
        print(diag)
        print("\nCanonical form for given Quadratic form is: ")
        print("{}*x**2+{}*y**2".format(diag[0,0],diag[1,1]),end="\n\n")
    
    elif n == 3:
        
        symmetric_matrix[0].append(expr.coeff(x**2))
        symmetric_matrix[0].append(int(0.5*(expr.coeff(x*y))))
        symmetric_matrix[0].append(int(0.5*(expr.coeff(x*z))))
        symmetric_matrix[1].append(int(0.5*(expr.coeff(x*y))))
        symmetric_matrix[1].append(expr.coeff(y**2))
        symmetric_matrix[1].append(int(0.5*(expr.coeff(y*z))))
        symmetric_matrix[2].append(int(0.5*(expr.coeff(x*z))))
        symmetric_matrix[2].append(int(0.5*(expr.coeff(y*z))))
        symmetric_matrix[2].append(expr.coeff(z**2))
        
        print("\nSymmetric matrix for given Quadratic form is: ",symmetric_matrix)
        
        SYMMETRIC = sp.Matrix(symmetric_matrix)
        CalculateEigenValues(SYMMETRIC)
        diag = CalculateEigenValues(SYMMETRIC)
        
        print(diag)
        print("\nCanonical form for given Quadratic form is: ")
        print("{}*x**2+{}*y**2+{}*z**2".format(diag[0,0],diag[1,1],diag[2,2]),end="\n\n")
        
main()


 **Q4 - Check whether the following matrices are diagonalizable or not using
python program**

In [7]:
arr = np.zeros((3, 3, 3), dtype = 'int')

arr[0] = [[-10, 11, -6],
          [-15, 16, -10],
          [-3, 3, -2]]

arr[1] = [[3, -1, 0],
          [-1, 2, -1],
          [0, -1, 3]]

arr[2] = [[1, -7, -1],
          [0, 1, 0],
          [0, 15, -2]]

n = len(arr)
for i in range(n):
  if len(eigenValues(arr[i])) == n:
    print(f'{i + 1}. Diagonalizable!')
  else:
    print(f'{i + 1}. Not Diagonalizable!')

1. Not Diagonalizable!
2. Diagonalizable!
3. Not Diagonalizable!


 **Q5 - Write a python program for the following matrices to find the domi-
nant eigen vector using power method and dominant eigen value using Rayleigh quotient?**

In [2]:
arr = [[[2, 1], [0, -4]]]

arr.append([[-5, 0, 0],
            [3, 7, 0],
            [4, -2, 3]])

arr.append([[1, 2, -2],
            [-2, 5, -2],
            [-6, 6, -3]])

arr = [np.array(i) for i in arr]
for i in range(len(arr)):
  n = len(arr[i])
  eigenVector = np.array([[1]] * n)
  for j in range(20):
    eigenVector = np.matmul(arr[i], eigenVector)
    eigenVector = np.round(eigenVector / max(eigenVector), 2)
  eigenValue = round(sum(np.matmul(arr[i], eigenVector) * eigenVector)[0] / (sum(eigenVector * eigenVector)[0]), 2)
  print(f'{i + 1}. Dominant Eigenvalue = {eigenValue}')
  print(f'Dominant Eigenvector = \n{eigenVector}', end = '\n\n')

1. Dominant Eigenvalue = -4.01
Dominant Eigenvector = 
[[-0.16]
 [ 1.  ]]

2. Dominant Eigenvalue = 6.99
Dominant Eigenvector = 
[[ 0.01]
 [ 1.  ]
 [-0.51]]

3. Dominant Eigenvalue = -0.33
Dominant Eigenvector = 
[[1.]
 [1.]
 [1.]]



 **Q6 - Write a python program for the following matrices to find the smallest
eigen vector using inverse power method and smallest eigen value using
Rayleigh quotient?**

In [6]:
arr = np.zeros((3, 3, 3), dtype = 'int')

arr[0] = [[2, 3, 1],
          [0, -1, 2],
          [0, 0, 3]]

arr[1] = [[3, 0, 0],
          [1, -1, 0],
          [0, 2, 8]]

arr[2] = [[1, 2, 0],
          [0, -7, 1],
          [0, 0, 0]]

for i in range(len(arr)):
  n = len(arr[i])
  eigenVector = np.array([[1]] * n)
  if np.linalg.det(arr[i]) != 0:
    inv = np.linalg.inv(arr[i])
  else:
    continue
  for j in range(20):
    eigenVector = np.matmul(inv, eigenVector)
    eigenVector = np.round(eigenVector / max(eigenVector), 2)
  eigenValue = round(sum(np.matmul(inv, eigenVector) * eigenVector)[0] / (sum(eigenVector * eigenVector)[0]), 2)
  print(f'{i + 1}. Smallest Eigenvalue = {eigenValue}')
  print(f'Smallest Eigenvector = \n{eigenVector}', end = '\n\n')

1. Smallest Eigenvalue = -1.0
Smallest Eigenvector = 
[[-1.]
 [ 1.]
 [ 0.]]

2. Smallest Eigenvalue = -1.0
Smallest Eigenvector = 
[[ 0.  ]
 [ 1.  ]
 [-0.22]]

